import Head from "next/head";

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>MiMiCuCu | Homepage</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className=''>Homepage</h1>
    </div>
  );
}
